### ISSUE TITLE
LMS Plugin list links to version 0.10

### ISSUE THREAD

**Issue by bungh0l10** [philippe44/LMS-PodcastExt#1]
Hi, 

LMS Plugin List has an outdated version which is not able to install.

_ [21-10-02 16:39:08.5205] Slim::Utils::PluginDownloader::_downloadError (266) unable to download PodcastExt from https://github.com/philippe44/LMS-PodcastExt/raw/main/PodcastExt-0.10.zip - 404 Not Found_

**Comment by philippe44** [comment]
Was an issue with mirroring on sourceforge
